name: yaansi
description: Yet another ANSI implementation! A utility package to color your terminal.
repository: https://github.com/akaiser/yaansi
screenshots:
  - description: Colored output example.
    path: images/example.png
version: 1.2.0

environment:
  sdk: ^3.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
