name: yaansi
description: Yet another ANSI implementation! A utility package to color your terminal.
repository: https://github.com/akaiser/yaansi
screenshots:
  - description: Colored output example.
    path: images/example.png
version: 1.3.0

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
