name: yaansi
description: Yet another ANSI implementation! A utility package to color your terminal.
repository: https://github.com/akaiser/yaansi
version: 0.9.0

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
