name: yaansi
description: Yet another ANSI implementation! A utility package to color your terminal.
repository: https://github.com/akaiser/yaansi
version: 1.0.2

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
